.gitignore, .travis.yml
It doesn't work properly against our module because of an upstream bug, and
the author plans to rewrite that code significantly; so just disable it
until it's properly fixed upstream.
=> travis: disable tflint for now

modules/alb_handling/main.tf
Removing unnecessary conditional logic.
=> && length(var.custom_listen_hosts) > 0 is redundant

README.md, main.tf, modules/alb_handling/main.tf, modules/alb_handling/variables.tf, variables.tf
Adding use_alb parameter when alb handling is used
Adding create_cname parameter for cname creation instead of IN A alias
We previously used length(var.lb_arn) to build local create boolean in the alb_handling submodule, this does not work in all Terraform environments as the lb_arn length cannot alwasy be computed. 
We currently have used cnames to create a record pointing to the load balancer. CNAME's can only have one occurrence of the same name. Using weighted IN A Alias multiple services can exist net to each other, also helping migrations.
=> Changes to alb handling

main.tf, modules/ecs_task_definition/container-definition.json, modules/ecs_task_definition/main.tf, modules/ecs_task_definition/output.tf, modules/ecs_task_definition/variables.tf, modules/iam/main.tf, modules/iam/variables.tf, variables.tf
This is an attempt to add basic volume support to tasks. Unfortunately
there are a few limitations right now because of Terraform syntax:
- Not all parameters to a Docker volume configuration are supported, as
some of them require nested maps
- Mountpoints are added to all containers in a task (i.e. they can't be
scoped to specific containers only)
- (new) Only a single Docker volume is supported, as the definition of its configuration is a block and we can't generate multiple blocks
=> Add volumes and mountpoints to tasks

README.md, main.tf, modules/alb_handling/main.tf, modules/alb_handling/output.tf, modules/alb_handling/variables.tf, variables.tf
Adding Cognito Authentication for HTTP Traffic to the ECS Service, by adding another listener rule for https which is valid. Also add Http to https redirect listener_rule enabled with var.redirect_http_to_https .
Many  services or stuff under development used to be behind a Nginx with htaccess enabled. The ALB Authentication with Cognito delivers an almost similar experience and users will be quite easy to maintain. This saves another nginx docker service to maintain.
=> Cognito Authentication Addition

main.tf, modules/iam/output.tf, modules/live_task_lookup/main.tf, modules/live_task_lookup/variables.tf
A dependency for the lambda iam role policy adding.. the This to make sure that the datasource lookup is not crashing at invoke because the policy was not there yet.. Never happened to me before..
Ignore_policy for the lambda, if people want to update their zip they will need to taint it. This way updates of the zip lambda should not cause huge Terraform Plans as the datasource will not be used when the lambda is updated.
=> lambda lookup policy dependency fix

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST.md
Adding GH templates ( https://docs.cloudposse.com/development/github/pull-requests/ ) for better issues and PRs. 
Forces everyone to follow the same clear route.
=> Adding Github templates Cloudposse style

outputs.tf
Added task execution role arn, task definition arn and task definition family to the outputs.
To provide ability to use those resources outside of module.
=> Add more output variables

main.tf, modules/ecs_service/main.tf, modules/ecs_service/variables.tf, variables.tf
**ECS** (default) -- Default, Rolling deployment type.
**CODE_DEPLOY** -- Blue/Green deployment style, controller by AWS CodeDeploy
_must be set if you want to deploy your ECS Service via CodeDeploy_
Example:
```
module "nginx_service" {
...
deployment_controller_type = "CODE_DEPLOY"
...
}
```
=> Add Deployment Type

modules/alb_handling/main.tf
Fix for https://github.com/blinkist/terraform-aws-airship-ecs-service/issues/52
=> Don't make HTTPS listener rules when HTTPS is disabled.

airship.tf/guide/ecs_service/README.md, airship.tf/guide/ecs_service/deployment.md, airship.tf/guide/ecs_service/ec2_specific.md, airship.tf/guide/ecs_service/ecs_cron_tasks.md, airship.tf/guide/ecs_service/healthcheck.md, airship.tf/guide/ecs_service/iam.md, airship.tf/guide/ecs_service/load_balancing.md, airship.tf/guide/ecs_service/logging.md, airship.tf/guide/ecs_service/networking.md, airship.tf/guide/ecs_service/scaling_capacity.md, airship.tf/guide/ecs_service/secrets_management.md, airship.tf/guide/ecs_service/service_discovery.md, main.tf, modules/ecs_container_definition/main.tf, modules/ecs_container_definition/variables.tf, variables.tf
Documentation used to be in different GH repo, moving it here should make it easier to maintain.
=> Adding documentation in the ecs repo itself

examples/with_nlb/main.tf
Registry won't publish currently.
```
Attribute redefined: The argument "filter" was already set at ./examples/with_nlb/main.tf:72,3-9. Each argument may be set only once. (in main.tf on line 77)
```
=> Fix Terraform Registry issues with examples

modules/ecs_container_definition/variables.tf
Rename faulty `container_command` to `command`
Breaks the module.
=> container_command breaking fix

.travis.yml
Have doc creation travis of airship.tf triggered by PR
This small build workflow is needed to get docs built when ecs service is PR'ed.
=> Travis cli install + proper config build trigger

examples/with_nlb/main.tf, examples/with_nlb/provider.tf
The example had an issue where the security group that allows traffic from the NLB to the ECS cluster/service would fail if there was more than one service being added. This was due to the data source used to look up the service not filtering the EIP's correctly.
This filter has been updated and the resource now is added correctly.
=> Resolved NLB network interface ip lookup issue

modules/iam/main.tf
It seems like AWS maybe doing some extra validation here but without 
this change, I am getting the below error [1]. As per the docs [2] when
using an ECS condition like ArnEquals, we need to ensure the value is
an actual valid ARN of the cluster, and not just the cluster id (name)
[1] `MalformedPolicyDocument: The policy failed legacy parsing`
[2] https://docs.aws.amazon.com/IAM/latest/UserGuide/list_amazonelasticcontainerservice.html
Have tested this branch and am no longer receiving the above error.
=> Fetch ECS task ARN for IAM policy conditional

modules/iam/main.tf
this change, I am getting the below error [1]. As per the docs [2] when
using an ECS condition like ArnEquals, we need to ensure the value is
an actual valid ARN of the cluster, and not just the cluster id (name)
[1] `MalformedPolicyDocument: The policy failed legacy parsing`
[2] https://docs.aws.amazon.com/IAM/latest/UserGuide/list_amazonelasticcontainerservice.html
=> It seems like AWS maybe doing some extra validation here but without

main.tf, modules/ecs_container_definition/main.tf, modules/ecs_container_definition/variables.tf, modules/iam/output.tf, outputs.tf, variables.tf
As per the documentation for Fargate using private docker registries[1]
this commit introduces a new variable
`repository_credentials_secret_arn` used to pass in the AWS Secrets
Manager path to your credentials secret. Note that this also requires
the ECS execution task role to have access to this secret.
[1] https://aws.amazon.com/blogs/compute/introducing-private-registry-authentication-support-for-aws-fargate/
I have tested this with `repository_credentials_secret_arn` set and unset in my caller module.
__NOTE__ this PR does not change the execution task role to allow permissions for AWS Secrets Manager access and instead leaves up to the caller to ensure this by using the `task_execution_role_arn` output and attaching a policy outside of this module.
=> Allow pulling images from private Docker registry

main.tf
If wanting to create an ECS task that does not have an ALB e.g. a 
scheduled task of some kind that doesn’t need an ALB, because we try and
do a lookup on a data source, I am currently getting [1]
If load_balancing_type is set to none, take it that we do *not* want to
create any resources in the ALB module.
[1] 
```
* module.ecs_service.module.alb_handling.data.aws_lb.main: 1 error occurred:
* module.ecs_service.module.alb_handling.data.aws_lb.main: data.aws_lb.main: Search returned 0 results, please revise so only one is returned
```
=> Only trigger ALB module if ALB != ‘none’

main.tf, modules/alb_handling/main.tf, modules/alb_handling/variables.tf, variables.tf
Added a variable for specifying port for the Target Group health check
By default it will be `traffic-port` (as is)
=> Health port variable

main.tf, modules/lambda_ecs_task_scheduler/main.tf, modules/lambda_ecs_task_scheduler/variables.tf, modules/live_task_lookup/main.tf, modules/live_task_lookup/variables.tf, variables.tf
This PR addresses https://github.com/blinkist/terraform-aws-airship-ecs-service/issues/84
Added variables for specifying runtime of lambdas for `live_task_lookup` module and `lambda_ecs_task_scheduler` module.
Default values are current
=> Lambda runtime variable
